version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-79-125-64-18.eu-west-1.compute.amazonaws.com
            database: d31qlndrf2554k
            user: qbcglnldsynmsv
            password: 2dfdebd64b04ef17d072ad02df941267e0369f90f0946836fa3e62c48947ab78
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
